#!/usr/bin/env python3
"""Generate samples_etaprime.yml from DAS for the eta'(958) -> 2mu2e CRAB campaign.

Same ParkingDoubleMuonLowMass stream as the upsilon campaign, but with two deliberate
differences (both decided during the 2026-07-30 session):

 1. GlobalTag is UNIFIED on 150X_dataRun3_v2 for 2022-2024 (instead of the campaign-matched
    124X/130X tags), matching the convention used in gen_samples_zllv.py: 150X_dataRun3_v2
    spans all Run3 data IOVs, so it supplies the right geometry/B-field/alignment for the
    vertex fits on 2022/2023 runs too. Validated on a real 2022 file before use.
    2025 stays on the PPD prompt tag 150X_dataRun3_Prompt_v1.

 2. 2022 C/D/E use PromptReco, NOT the 10Dec2022 reReco. (For ParkingDoubleMuonLowMass there
    is no 22Sep2023 reReco for C/D/E -- that only exists for F/G here, unlike the /Muon PD.)
    Per PPD, prompt data must include ALL processing versions -> Run2022D has both v1 and v2.

Era B is excluded everywhere. 2026 is excluded: its MiniAOD is written by CMSSW_16_0_X and a
15_0_15 build cannot read it (hard FormatIncompatibility).

Run with cmsenv + proxy:  python3 gen_samples_etaprime.py > samples_etaprime.yml
"""
import subprocess

CERT = "https://cms-service-dqmdc.web.cern.ch/CAF/certification"
GOLDEN = {
    22: CERT + "/Collisions22/Cert_Collisions2022_355100_362760_Golden.json",
    23: CERT + "/Collisions23/Cert_Collisions2023_366442_370790_Golden.json",
    24: CERT + "/Collisions24/Cert_Collisions2024_378981_386951_Golden.json",
    25: CERT + "/Collisions25/Cert_Collisions2025_391658_398903_Golden.json",
}
GT_RUN3   = "150X_dataRun3_v2"          # spans all Run3 data IOVs (2022-2024)
GT_PROMPT = "150X_dataRun3_Prompt_v1"   # 2025 prompt

# sample -> (stems expanded over parts 0..7, GT, golden-year)
SAMPLES = {
    # --- 2022: C/D/E PromptReco (D has v1+v2), F/G 22Sep2023 reReco ---
    "data_Run2022C": (["Run2022C-PromptReco"], GT_RUN3, 22),
    "data_Run2022D": (["Run2022D-PromptReco"], GT_RUN3, 22),   # picks up v1 AND v2
    "data_Run2022E": (["Run2022E-PromptReco"], GT_RUN3, 22),
    "data_Run2022F": (["Run2022F-22Sep2023"],  GT_RUN3, 22),
    "data_Run2022G": (["Run2022G-22Sep2023"],  GT_RUN3, 22),
    # --- 2023: 22Sep2023 reReco, C and D split into disjoint run ranges ---
    "data_Run2023C": (["Run2023C-22Sep2023_v1", "Run2023C-22Sep2023_v2",
                       "Run2023C-22Sep2023_v3", "Run2023C-22Sep2023_v4"], GT_RUN3, 23),
    "data_Run2023D": (["Run2023D-22Sep2023_v1", "Run2023D-22Sep2023_v2"], GT_RUN3, 23),
    # --- 2024: MINIv6NANOv15 (the v15 production) ---
    "data_Run2024C": (["Run2024C-MINIv6NANOv15"], GT_RUN3, 24),
    "data_Run2024D": (["Run2024D-MINIv6NANOv15"], GT_RUN3, 24),
    "data_Run2024E": (["Run2024E-MINIv6NANOv15"], GT_RUN3, 24),
    "data_Run2024F": (["Run2024F-MINIv6NANOv15"], GT_RUN3, 24),
    "data_Run2024G": (["Run2024G-MINIv6NANOv15"], GT_RUN3, 24),
    "data_Run2024H": (["Run2024H-MINIv6NANOv15"], GT_RUN3, 24),
    "data_Run2024I": (["Run2024I-MINIv6NANOv15", "Run2024I-MINIv6NANOv15_v2"], GT_RUN3, 24),
    # --- 2025: PromptReco (C and F have disjoint v1+v2) ---
    "data_Run2025C": (["Run2025C-PromptReco"], GT_PROMPT, 25),
    "data_Run2025D": (["Run2025D-PromptReco"], GT_PROMPT, 25),
    "data_Run2025E": (["Run2025E-PromptReco"], GT_PROMPT, 25),
    "data_Run2025F": (["Run2025F-PromptReco"], GT_PROMPT, 25),
    "data_Run2025G": (["Run2025G-PromptReco"], GT_PROMPT, 25),
}

BAD = ("TrkRadDamage", "ECAL", "HCAL")   # detector-study reprocessings


def das(stem, part):
    q = "dataset=/ParkingDoubleMuonLowMass%d/%s*/MINIAOD" % (part, stem)
    out = subprocess.run(["dasgoclient", "-query", q], capture_output=True, text=True).stdout
    return [l.strip() for l in out.splitlines() if l.strip() and not any(b in l for b in BAD)]


print("# Auto-generated by gen_samples_etaprime.py. eta'(958) -> 2mu2e campaign.")
print("# GT unified on 150X_dataRun3_v2 for 2022-2024 (zllv convention); 2025 = prompt tag.")
print("# 2022 C/D/E = PromptReco (no 22Sep2023 exists for these in Parking); D includes v1+v2.")
print("# Era B and 2026 excluded. lumimask = golden-JSON URL (CRAB reads URLs directly).")
print("common:")
print("  data: {splitting: 50}")
print("  mc:   {splitting: 1}")
print("samples:")
for name, (stems, gt, gy) in SAMPLES.items():
    datasets = sorted(set(d for stem in stems for part in range(8) for d in das(stem, part)))
    if not datasets:
        print("  # WARNING: no datasets found for %s (stems=%s)" % (name, stems))
        continue
    print("  %s:" % name)
    print("    isMC: False")
    print("    mode: 'lowpt'")
    print("    globaltag: %s" % gt)
    print("    lumimask: %s" % GOLDEN[gy])
    print("    datasets:")
    for d in datasets:
        print("      - %s" % d)
