#!/usr/bin/env python3
"""Generate samples_upsilon.yml from DAS for the Upsilon->4mu/2mu2e CRAB campaign.

Queries the exact per-part MINIAOD dataset names (versions scatter across parts, so we
do NOT use a %d template) for the chosen campaign set, EXCLUDING era B. 2026 is descoped.

GlobalTags and golden-JSON lumimasks are the official PPD Run-3 recommendations
(PPD_Run3_<year>_SummaryTable slides) cross-checked against each dataset's production
global_tag in DAS, and the latest golden JSON in
  https://cms-service-dqmdc.web.cern.ch/CAF/certification/Collisions<YY>/

Run on lxplus/cmslpc with a valid proxy + cmsenv:
    python3 gen_samples_upsilon.py > samples_upsilon.yml
"""
import subprocess

CERT = "https://cms-service-dqmdc.web.cern.ch/CAF/certification"
GOLDEN = {
    22: CERT + "/Collisions22/Cert_Collisions2022_355100_362760_Golden.json",
    23: CERT + "/Collisions23/Cert_Collisions2023_366442_370790_Golden.json",
    24: CERT + "/Collisions24/Cert_Collisions2024_378981_386951_Golden.json",
    25: CERT + "/Collisions25/Cert_Collisions2025_391658_398903_Golden.json",
}

# per-sample (year+campaign) config:
#   stems    : Run<era>-<campaign> prefixes expanded over parts 0..7 (wildcarded in DAS)
#   gt       : recommended analysis GlobalTag (PPD, matched to the format actually on DAS)
#   golden   : golden-JSON year key
# 2022 C/D/E = 10Dec2022 ReReco (prod 124X) -> PPD ReRECO GT 124X_dataRun3_v15
# 2022 F/G   = 22Sep2023 ReMini (prod 130X) -> PPD ReMini GT 130X_dataRun3_PromptAnalysis_v1
# 2023 C/D   = 22Sep2023 ReMini (prod 130X) -> PPD ReMini GT 130X_dataRun3_PromptAnalysis_v1
# 2024 C-I   = MINIv6NANOv15 (prod 150X)    -> PPD v15 GT 150X_dataRun3_v2
# 2025 C-G   = PromptReco (prod 150X)       -> PPD v15 prompt GT 150X_dataRun3_Prompt_v1
GT_2022_RERECO = "124X_dataRun3_v15"
GT_2022_REMINI = "130X_dataRun3_PromptAnalysis_v1"
GT_2023        = "130X_dataRun3_PromptAnalysis_v1"
GT_2024_V15    = "150X_dataRun3_v2"
GT_2025_PROMPT = "150X_dataRun3_Prompt_v1"

SAMPLES = {
    "data_Run2022C": (["Run2022C-10Dec2022"], GT_2022_RERECO, 22),
    "data_Run2022D": (["Run2022D-10Dec2022"], GT_2022_RERECO, 22),
    "data_Run2022E": (["Run2022E-10Dec2022"], GT_2022_RERECO, 22),
    "data_Run2022F": (["Run2022F-22Sep2023"], GT_2022_REMINI, 22),
    "data_Run2022G": (["Run2022G-22Sep2023"], GT_2022_REMINI, 22),
    "data_Run2023C": (["Run2023C-22Sep2023_v1", "Run2023C-22Sep2023_v2",
                       "Run2023C-22Sep2023_v3", "Run2023C-22Sep2023_v4"], GT_2023, 23),
    "data_Run2023D": (["Run2023D-22Sep2023_v1", "Run2023D-22Sep2023_v2"], GT_2023, 23),
    "data_Run2024C": (["Run2024C-MINIv6NANOv15"], GT_2024_V15, 24),
    "data_Run2024D": (["Run2024D-MINIv6NANOv15"], GT_2024_V15, 24),
    "data_Run2024E": (["Run2024E-MINIv6NANOv15"], GT_2024_V15, 24),
    "data_Run2024F": (["Run2024F-MINIv6NANOv15"], GT_2024_V15, 24),
    "data_Run2024G": (["Run2024G-MINIv6NANOv15"], GT_2024_V15, 24),
    "data_Run2024H": (["Run2024H-MINIv6NANOv15"], GT_2024_V15, 24),
    "data_Run2024I": (["Run2024I-MINIv6NANOv15", "Run2024I-MINIv6NANOv15_v2"], GT_2024_V15, 24),
    "data_Run2025C": (["Run2025C-PromptReco"], GT_2025_PROMPT, 25),
    "data_Run2025D": (["Run2025D-PromptReco"], GT_2025_PROMPT, 25),
    "data_Run2025E": (["Run2025E-PromptReco"], GT_2025_PROMPT, 25),
    "data_Run2025F": (["Run2025F-PromptReco"], GT_2025_PROMPT, 25),
    "data_Run2025G": (["Run2025G-PromptReco"], GT_2025_PROMPT, 25),
}


def das(stem, part):
    q = "dataset=/ParkingDoubleMuonLowMass%d/%s*/MINIAOD" % (part, stem)
    out = subprocess.run(["dasgoclient", "-query", q], capture_output=True, text=True).stdout
    return [l.strip() for l in out.splitlines() if l.strip()]


print("# Auto-generated by gen_samples_upsilon.py from DAS + PPD Run-3 summary tables.")
print("# Exact per-part dataset names (versions scatter across parts). Era B and 2026 excluded.")
print("# GTs: PPD-recommended, matched to each dataset's production global_tag. Golden JSON = latest")
print("# per year (CRAB accepts the URL directly). 2024 uses the MINIv6NANOv15 (v15) production.")
print("common:")
print("  data:")
print("    splitting: 20          # files/job (tune per era)")
print("  mc:")
print("    splitting: 1")
print("samples:")
for name, (stems, gt, gy) in SAMPLES.items():
    datasets = sorted(set(d for stem in stems for part in range(8) for d in das(stem, part)))
    if not datasets:
        print("  # WARNING: no datasets found for %s (stems=%s)" % (name, stems))
        continue
    print("  %s:" % name)
    print("    isMC: False")
    print("    mode: '4l'")
    print("    globaltag: %s" % gt)
    print("    lumimask: %s" % GOLDEN[gy])
    print("    datasets:")
    for d in datasets:
        print("      - %s" % d)
