#!/usr/bin/env python3
"""Generate samples_zllv.yml from DAS for the Z->llV (V->hh) CRAB campaign.

/Muon0  -> mumu channel  (single-muon HLT)
/EGamma0-> ee   channel  (single-electron HLT)
2024: MINIv6NANOv15 (v15) reReco, GT 150X_dataRun3_v2, golden 2024.
2025: PromptReco,            GT 150X_dataRun3_Prompt_v1, golden 2025 (C,F have v1+v2 disjoint).
Special detector-study processings (TrkRadDamage, ECAL*, ...) are excluded.

Run with cmsenv + proxy:  python3 gen_samples_zllv.py > samples_zllv.yml
"""
import subprocess

CERT = "https://cms-service-dqmdc.web.cern.ch/CAF/certification"
GOLDEN_2024 = CERT + "/Collisions24/Cert_Collisions2024_378981_386951_Golden.json"
GOLDEN_2025 = CERT + "/Collisions25/Cert_Collisions2025_391658_398903_Golden.json"
GT_2024 = "150X_dataRun3_v2"          # PPD v15 (MINIv6NANOv15)
GT_2025 = "150X_dataRun3_Prompt_v1"   # PPD prompt

TRIG = {"mumu": "HLT_IsoMu24_v* HLT_Mu50_v*", "ee": "HLT_Ele30_WPTight_Gsf_v*"}

# sample -> (PD, channel, list of Run<era>-<campaign> stems, GT, golden)
SAMPLES = {
    "data_Muon0_2024":   ("Muon0",   "mumu",
        ["Run2024C-MINIv6NANOv15", "Run2024D-MINIv6NANOv15", "Run2024E-MINIv6NANOv15",
         "Run2024F-MINIv6NANOv15", "Run2024G-MINIv6NANOv15", "Run2024H-MINIv6NANOv15",
         "Run2024I-MINIv6NANOv15"], GT_2024, GOLDEN_2024),
    "data_EGamma0_2024": ("EGamma0", "ee",
        ["Run2024C-MINIv6NANOv15", "Run2024D-MINIv6NANOv15", "Run2024E-MINIv6NANOv15",
         "Run2024F-MINIv6NANOv15", "Run2024G-MINIv6NANOv15", "Run2024H-MINIv6NANOv15",
         "Run2024I-MINIv6NANOv15"], GT_2024, GOLDEN_2024),
    "data_Muon0_2025":   ("Muon0",   "mumu",
        ["Run2025B-PromptReco", "Run2025C-PromptReco", "Run2025D-PromptReco",
         "Run2025E-PromptReco", "Run2025F-PromptReco", "Run2025G-PromptReco"], GT_2025, GOLDEN_2025),
    "data_EGamma0_2025": ("EGamma0", "ee",
        ["Run2025B-PromptReco", "Run2025C-PromptReco", "Run2025D-PromptReco",
         "Run2025E-PromptReco", "Run2025F-PromptReco", "Run2025G-PromptReco"], GT_2025, GOLDEN_2025),
}


def das(pd, stem):
    q = "dataset=/%s/%s*/MINIAOD" % (pd, stem)
    out = subprocess.run(["dasgoclient", "-query", q], capture_output=True, text=True).stdout
    # exclude detector-study reprocessings
    bad = ("TrkRadDamage", "ECAL", "HCAL")
    return [l.strip() for l in out.splitlines() if l.strip() and not any(b in l for b in bad)]


print("# Auto-generated by gen_samples_zllv.py. /Muon0 -> mumu, /EGamma0 -> ee.")
print("# 2024 = MINIv6NANOv15 (GT 150X_dataRun3_v2); 2025 = PromptReco (GT 150X_dataRun3_Prompt_v1).")
print("# lumimask = golden-JSON URL (swap to a local path if preferred).")
print("common:")
print("  data: {splitting: 30}")
print("  mc:   {splitting: 1}")
print("samples:")
for name, (pd, ch, stems, gt, golden) in SAMPLES.items():
    datasets = sorted(set(d for stem in stems for d in das(pd, stem)))
    if not datasets:
        print("  # WARNING: no datasets for %s" % name); continue
    print("  %s:" % name)
    print("    isMC: False")
    print("    mode: '%s'" % ch)
    print("    trigger: '%s'" % TRIG[ch])
    print("    globaltag: %s" % gt)
    print("    lumimask: %s" % golden)
    print("    datasets:")
    for d in datasets:
        print("      - %s" % d)
